-- tables
DROP TABLE Cena_Produktu CASCADE CONSTRAINTS;

DROP TABLE Dostawca CASCADE CONSTRAINTS;

DROP TABLE Dział CASCADE CONSTRAINTS;

DROP TABLE Kategoria_Produktu CASCADE CONSTRAINTS;

DROP TABLE Magazyn CASCADE CONSTRAINTS;

DROP TABLE Ocena_Od_Klienta CASCADE CONSTRAINTS;

DROP TABLE Oddział CASCADE CONSTRAINTS;

DROP TABLE Pracownik CASCADE CONSTRAINTS;

DROP TABLE Produkt CASCADE CONSTRAINTS;

DROP TABLE Produkt_Zamówienie CASCADE CONSTRAINTS;

DROP TABLE Promocje CASCADE CONSTRAINTS;

DROP TABLE Reklamacja CASCADE CONSTRAINTS;

DROP TABLE Sprzedaż CASCADE CONSTRAINTS;

DROP TABLE Zamówienia CASCADE CONSTRAINTS;
	
