declare
    l_dostawcow number;
    l_oddzialow number;
    l_dzialow number;
    l_kategorii number;
    l_kasjerow number;
    l_produktow number;
    l_wpisow_magazynu number;
begin
    SELECT max(id) INTO l_dostawcow FROM zbd_staging.dostawca;
    SELECT max(id) INTO l_oddzialow FROM zbd_staging.oddział;
    SELECT max(id) INTO l_dzialow FROM zbd_staging.dział;
    SELECT max(id) INTO l_kategorii FROM zbd_staging.kategoria_produktu;
    SELECT max(id) INTO l_kasjerow FROM zbd_staging.pracownik;
    SELECT max(id) INTO l_produktow FROM zbd_staging.produkt;
    SELECT max(id) INTO l_wpisow_magazynu FROM zbd_staging.magazyn;

    -- Dostawcy - samo przepisanie nazw:
    INSERT INTO zbd_staging.dostawca (id, nazwa)
    SELECT id+l_dostawcow, nazwa
    FROM zbd_source.dostawca;
    
	--  Oddzialy - rozdzielenie "miasto, ulica, województwo" na 3 kolumny:
	declare
	  l_miejscowosc varchar(50);
	  l_ulica_i_numer varchar(50);
	  l_wojewodztwo varchar(50);
	begin
	  for wiersz in (select id, nazwa as nazwa_z_numerem_oddzialu, adres as pelny_adres from zbd_source.oddzial) loop
		-- INSTR znajduje w stringu wystąpienie innego stringa, tutaj z "New York City, Holywood bl, woj. Śląskie" wyciągnie "New York City":
		l_miejscowosc := SUBSTR(wiersz.pelny_adres, 0, INSTR(wiersz.pelny_adres, ', ')-1);
		
		-- Substring od pierwszego (druga jedynka, pierwsza jedynka to indeks w stringu od którego zaczynamy szukać) wystąpienia ', '
		-- o długości (a nie do - ostatni parametr SUBSTR to ilość znaków do wyciągnięcia, czyli tutaj pozycja drugiego ', ' minus pozycja pierwszego ', ':
		l_ulica_i_numer := SUBSTR(wiersz.pelny_adres, INSTR(wiersz.pelny_adres, ', ', 1, 1)+2, INSTR(wiersz.pelny_adres, ', ', 1, 2)-INSTR(wiersz.pelny_adres, ', ', 1, 1)-2);
		
		l_wojewodztwo := SUBSTR(wiersz.pelny_adres, INSTR(wiersz.pelny_adres, ', ', 1, 2)+2, length(wiersz.pelny_adres)-INSTR(wiersz.pelny_adres, ', ', 1, 2)-1);
		
		--dbms_output.put_line(l_miejscowosc || '    ' || l_ulica_i_numer || '    ' || l_wojewodztwo);
        
		INSERT INTO zbd_staging.oddział (id, nazwa, miasto, województwo, ulica_i_numer)
		VALUES (wiersz.id+l_oddzialow, wiersz.nazwa_z_numerem_oddzialu, l_miejscowosc, l_wojewodztwo, l_ulica_i_numer);
        
	  end loop;
	end;

	-- Oracle PL/SQL nie oferuje niczego co pozwalałoby odwzorować HashMap<String, ArrayList<String>>
	-- "lokalnie", w obrębie skryptu, pozostaje więc:
	ALTER TABLE spis_kategorii DROP CONSTRAINT kategoria_a_dzial;

	DROP TABLE spis_kategorii;
	DROP TABLE spis_dzialow;

	CREATE TABLE spis_dzialow (
		id number(12) GENERATED BY DEFAULT ON NULL AS IDENTITY,
		CONSTRAINT nazwa_dzialu_pk PRIMARY KEY (id),
		
		nazwa varchar2(40)
	);

	CREATE TABLE spis_kategorii (
		id number(12) GENERATED BY DEFAULT ON NULL AS IDENTITY,
		CONSTRAINT spis_kategorii_pk PRIMARY KEY (id),
		
		nazwa varchar2(40),
		id_odpowiadajacego_dzialu number(12)
	);

	ALTER TABLE spis_kategorii ADD CONSTRAINT kategoria_a_dzial
		FOREIGN KEY (id_odpowiadajacego_dzialu)
			REFERENCES spis_dzialow (id) ON DELETE CASCADE;

	INSERT INTO spis_dzialow (nazwa) VALUES ('AGD');
	INSERT INTO spis_kategorii (nazwa, id_odpowiadajacego_dzialu) VALUES ('lodówki', 1);
	INSERT INTO spis_kategorii (nazwa, id_odpowiadajacego_dzialu) VALUES ('suszarki', 1);
	INSERT INTO spis_kategorii (nazwa, id_odpowiadajacego_dzialu) VALUES ('kuchenki gazowe', 1);
	INSERT INTO spis_kategorii (nazwa, id_odpowiadajacego_dzialu) VALUES ('kuchenki mikrofalowe', 1);
	INSERT INTO spis_kategorii (nazwa, id_odpowiadajacego_dzialu) VALUES ('czajniki elektryczne', 1);
	INSERT INTO spis_kategorii (nazwa, id_odpowiadajacego_dzialu) VALUES ('golarki i maszynki elektryczne', 1);
	INSERT INTO spis_kategorii (nazwa, id_odpowiadajacego_dzialu) VALUES ('okapy', 1);
	INSERT INTO spis_kategorii (nazwa, id_odpowiadajacego_dzialu) VALUES ('zmywarki', 1);

	INSERT INTO spis_dzialow (nazwa) VALUES ('RTV');
	INSERT INTO spis_kategorii (nazwa, id_odpowiadajacego_dzialu) VALUES ('telewizory', 2);
	INSERT INTO spis_kategorii (nazwa, id_odpowiadajacego_dzialu) VALUES ('konsole', 2);
	INSERT INTO spis_kategorii (nazwa, id_odpowiadajacego_dzialu) VALUES ('sprzęt audio', 2);
	INSERT INTO spis_kategorii (nazwa, id_odpowiadajacego_dzialu) VALUES ('kable i przejściówki', 2);
	INSERT INTO spis_kategorii (nazwa, id_odpowiadajacego_dzialu) VALUES ('telefony i tablety', 2);

	INSERT INTO spis_dzialow (nazwa) VALUES ('artykuły spożywcze');
	INSERT INTO spis_kategorii (nazwa, id_odpowiadajacego_dzialu) VALUES ('nabiał', 3);
	INSERT INTO spis_kategorii (nazwa, id_odpowiadajacego_dzialu) VALUES ('pieczywo', 3);
	INSERT INTO spis_kategorii (nazwa, id_odpowiadajacego_dzialu) VALUES ('ryby', 3);
	INSERT INTO spis_kategorii (nazwa, id_odpowiadajacego_dzialu) VALUES ('mięso i wędliny', 3);
	INSERT INTO spis_kategorii (nazwa, id_odpowiadajacego_dzialu) VALUES ('mrożonki', 3);
	INSERT INTO spis_kategorii (nazwa, id_odpowiadajacego_dzialu) VALUES ('produkty zbożowe', 3);
	INSERT INTO spis_kategorii (nazwa, id_odpowiadajacego_dzialu) VALUES ('warzywa i owoce', 3);
	INSERT INTO spis_kategorii (nazwa, id_odpowiadajacego_dzialu) VALUES ('słodycze', 3);
	INSERT INTO spis_kategorii (nazwa, id_odpowiadajacego_dzialu) VALUES ('napoje', 3);
	INSERT INTO spis_kategorii (nazwa, id_odpowiadajacego_dzialu) VALUES ('przekąski', 3);

	INSERT INTO spis_dzialow (nazwa) VALUES ('alkohole');
	INSERT INTO spis_kategorii (nazwa, id_odpowiadajacego_dzialu) VALUES ('wina czerwone', 4);
	INSERT INTO spis_kategorii (nazwa, id_odpowiadajacego_dzialu) VALUES ('wina białe', 4);
	INSERT INTO spis_kategorii (nazwa, id_odpowiadajacego_dzialu) VALUES ('whiskey', 4);
	INSERT INTO spis_kategorii (nazwa, id_odpowiadajacego_dzialu) VALUES ('likiery', 4);
	INSERT INTO spis_kategorii (nazwa, id_odpowiadajacego_dzialu) VALUES ('wódki smakowe', 4);
	INSERT INTO spis_kategorii (nazwa, id_odpowiadajacego_dzialu) VALUES ('wódki czyste', 4);
	INSERT INTO spis_kategorii (nazwa, id_odpowiadajacego_dzialu) VALUES ('piwa', 4);

	INSERT INTO spis_dzialow (nazwa) VALUES ('kosmetyki');  
	INSERT INTO spis_kategorii (nazwa, id_odpowiadajacego_dzialu) VALUES ('artykuły do kąpieli', 5);
	INSERT INTO spis_kategorii (nazwa, id_odpowiadajacego_dzialu) VALUES ('kremy', 5);
	INSERT INTO spis_kategorii (nazwa, id_odpowiadajacego_dzialu) VALUES ('higiena jamy ustnej', 5);
	INSERT INTO spis_kategorii (nazwa, id_odpowiadajacego_dzialu) VALUES ('artykuły do makijażu', 5);
	INSERT INTO spis_kategorii (nazwa, id_odpowiadajacego_dzialu) VALUES ('perfumy', 5);

	INSERT INTO spis_dzialow (nazwa) VALUES ('zabawki');
	INSERT INTO spis_kategorii (nazwa, id_odpowiadajacego_dzialu) VALUES ('materiały artystyczne', 6);
	INSERT INTO spis_kategorii (nazwa, id_odpowiadajacego_dzialu) VALUES ('zabawki interaktywne', 6);
	INSERT INTO spis_kategorii (nazwa, id_odpowiadajacego_dzialu) VALUES ('układanki', 6);
	INSERT INTO spis_kategorii (nazwa, id_odpowiadajacego_dzialu) VALUES ('lalki i zabawki pluszowe', 6);
	INSERT INTO spis_kategorii (nazwa, id_odpowiadajacego_dzialu) VALUES ('pojazdy', 6);

	INSERT INTO spis_dzialow (nazwa) VALUES ('artykuły papiernicze');
	INSERT INTO spis_kategorii (nazwa, id_odpowiadajacego_dzialu) VALUES ('szkolne', 7);
	INSERT INTO spis_kategorii (nazwa, id_odpowiadajacego_dzialu) VALUES ('biurowe', 7);
	INSERT INTO spis_kategorii (nazwa, id_odpowiadajacego_dzialu) VALUES ('artystyczne', 7);

	INSERT INTO spis_dzialow (nazwa) VALUES ('dom');
	INSERT INTO spis_kategorii (nazwa, id_odpowiadajacego_dzialu) VALUES ('dekoracje i akcesoria', 8);
	INSERT INTO spis_kategorii (nazwa, id_odpowiadajacego_dzialu) VALUES ('oświetlenie', 8);
	INSERT INTO spis_kategorii (nazwa, id_odpowiadajacego_dzialu) VALUES ('tekstylia', 8);
	INSERT INTO spis_kategorii (nazwa, id_odpowiadajacego_dzialu) VALUES ('szafki, regały, stojaki', 8);

	INSERT INTO spis_dzialow (nazwa) VALUES ('ogród');
	INSERT INTO spis_kategorii (nazwa, id_odpowiadajacego_dzialu) VALUES ('dekoracje ogrodowe', 9);
	INSERT INTO spis_kategorii (nazwa, id_odpowiadajacego_dzialu) VALUES ('grille i akcesoria', 9);
	INSERT INTO spis_kategorii (nazwa, id_odpowiadajacego_dzialu) VALUES ('meble ogrodowe', 9);
	INSERT INTO spis_kategorii (nazwa, id_odpowiadajacego_dzialu) VALUES ('oświetlenie ogrodowe', 9);

	INSERT INTO spis_dzialow (nazwa) VALUES ('produkty do sprzątania');
	INSERT INTO spis_kategorii (nazwa, id_odpowiadajacego_dzialu) VALUES ('pranie i płukanie', 10);
	INSERT INTO spis_kategorii (nazwa, id_odpowiadajacego_dzialu) VALUES ('środki czystości, detergenty', 10);
	INSERT INTO spis_kategorii (nazwa, id_odpowiadajacego_dzialu) VALUES ('środki do samochodu i warsztatu', 10);
	INSERT INTO spis_kategorii (nazwa, id_odpowiadajacego_dzialu) VALUES ('suszenie i prasowanie', 10);
	INSERT INTO spis_kategorii (nazwa, id_odpowiadajacego_dzialu) VALUES ('do podłóg', 10);
	INSERT INTO spis_kategorii (nazwa, id_odpowiadajacego_dzialu) VALUES ('do okien', 10);
	INSERT INTO spis_kategorii (nazwa, id_odpowiadajacego_dzialu) VALUES ('do mebli', 10);

	INSERT INTO spis_dzialow (nazwa) VALUES ('multimedia');
	INSERT INTO spis_kategorii (nazwa, id_odpowiadajacego_dzialu) VALUES ('gry konsolowe', 11);
	INSERT INTO spis_kategorii (nazwa, id_odpowiadajacego_dzialu) VALUES ('gry PC', 11);
	INSERT INTO spis_kategorii (nazwa, id_odpowiadajacego_dzialu) VALUES ('filmy', 11);
	INSERT INTO spis_kategorii (nazwa, id_odpowiadajacego_dzialu) VALUES ('muzyka', 11);
	INSERT INTO spis_kategorii (nazwa, id_odpowiadajacego_dzialu) VALUES ('książki', 11);

	INSERT INTO spis_dzialow (nazwa) VALUES ('odzież');
	INSERT INTO spis_kategorii (nazwa, id_odpowiadajacego_dzialu) VALUES ('odzież sportowa', 12);
	INSERT INTO spis_kategorii (nazwa, id_odpowiadajacego_dzialu) VALUES ('moda damska', 12);
	INSERT INTO spis_kategorii (nazwa, id_odpowiadajacego_dzialu) VALUES ('moda męska', 12);

	INSERT INTO spis_dzialow (nazwa) VALUES ('obuwie');
	INSERT INTO spis_kategorii (nazwa, id_odpowiadajacego_dzialu) VALUES ('dla dzieci', 13);
	INSERT INTO spis_kategorii (nazwa, id_odpowiadajacego_dzialu) VALUES ('sportowe', 13);
	INSERT INTO spis_kategorii (nazwa, id_odpowiadajacego_dzialu) VALUES ('obuwie męskie', 13);
	INSERT INTO spis_kategorii (nazwa, id_odpowiadajacego_dzialu) VALUES ('obuwie damskie', 13);

	-- Działy - samo przepisanie nazw, ale wszystkich i bez powtarzania, inaczej spowoduje to problemy
	-- podczas dopasowania (tabela "dział" generowana skryptem nie będzie użyta, właśnie ze względu na pominięcia i powtórzenia):
	INSERT INTO zbd_staging.dział (id, nazwa)
	SELECT id+l_dzialow, nazwa
	FROM zbd_source.spis_dzialow;
    
	--  Typ/kategoria produktu - powyższe mapowania są konieczne do sensownego przypisania, to informacja której brakuje w tabeli źródłowej
	declare
	  id_dzialu number(12);
	begin
	  for wiersz in (SELECT id, nazwa FROM zbd_source.typ_produktu) LOOP
		
		SELECT id_odpowiadajacego_dzialu INTO id_dzialu FROM spis_kategorii
		WHERE nazwa = wiersz.nazwa;
        
		INSERT INTO zbd_staging.kategoria_produktu (id, id_działu, nazwa)
		VALUES (wiersz.id+l_kategorii, id_dzialu, wiersz.nazwa);
		
	  end loop;
	end;
    
	-- Kasjerzy:
	INSERT INTO zbd_staging.pracownik (id, imię, nazwisko)
	SELECT id+l_kasjerow, imie, nazwisko
	FROM zbd_source.kasjer;
    
    -- Produkty:
	INSERT INTO zbd_staging.produkt (id, id_kategorii, nazwa, id_działu)
	SELECT id+l_produktow, id_typu_produktu, nazwa, id_dzialu
	FROM zbd_source.produkt;
    
    -- Wpisy o stanie magazynu:
	INSERT INTO zbd_staging.magazyn (id_oddziału, id_produktu, liczba_produktów, czas)
	SELECT id_oddzialu, id_produktu, liczba_sztuk, aktualny_na
	FROM zbd_source.obecny_stan_magazynu;

end;

