-- Jeśli po wykonaniu jakichś instrukcji insertowania danych nie widać zmian to jeszcze commit trzeba nakliknąć

-- Dostawcy - samo przepisanie nazw:
INSERT INTO zbd_staging.dostawca (nazwa)
SELECT nazwa
FROM zbd_source.dostawca;

-- Działy - samo przepisanie nazw:
INSERT INTO zbd_staging.dział (nazwa)
SELECT nazwa
FROM zbd_source.dzial;

--INSERT INTO zbd_staging.oddział (nazwa, substr(miejscowosc_przecinek_spacja, 1, length(miejscowosc_przecinek_spacja)-2), 'woj', 'ul num')
--SELECT nazwa, regexp_substr(adres, '(\w+),\s', 1, 1) as miejscowosc_przecinek_spacja, nazwa, nazwa
--FROM zbd_source.oddzial;
--select adres, substr(adres, 1, length(adres)-2) from zbd_source.oddzial;
--select 'ab, cd, ef', INSTR('ab, cd, ef', ', ', 1, 1) as pierwsze, INSTR('ab, cd, ef', ', ', 1, 2) as drugie from zbd_source.oddzial;
--select adres, SUBSTR(adres, INSTR(adres, ', ', 1, 2)+2, length(adres)-INSTR(adres, ', ', 1, 2)-1) as wynik from zbd_source.oddzial;

--  Oddziały - rozdzielenie "miasto, ulica, województwo" na 3 kolumny:
declare
  l_miejscowosc varchar(50);
  l_ulica_i_numer varchar(50);
  l_wojewodztwo varchar(50);
begin
  for wiersz in (select nazwa as nazwa_z_numerem_oddzialu, adres as pelny_adres from zbd_source.oddzial) loop
    -- INSTR znajduje w stringu wystąpienie innego stringa, tutaj z "New York City, Holywood bl, woj. Śląskie" wyciągnie "New York City"
    l_miejscowosc := SUBSTR(wiersz.pelny_adres, 0, INSTR(wiersz.pelny_adres, ', ')-1);
    
    -- Substring od pierwszego (druga jedynka, pierwsza jedynka to indeks w stringu od którego zaczynamy szukać) wystąpienia ', '
    -- o długości (a nie: do, bo drugi ostatni parametr SUBSTR to ilość znaków do wyciągnięcia, czyli pozycja drugiego ', ' minus pozycja pierwszego ', '
    l_ulica_i_numer := SUBSTR(wiersz.pelny_adres, INSTR(wiersz.pelny_adres, ', ', 1, 1)+2, INSTR(wiersz.pelny_adres, ', ', 1, 2)-INSTR(wiersz.pelny_adres, ', ', 1, 1)-2);
    
    l_wojewodztwo := SUBSTR(wiersz.pelny_adres, INSTR(wiersz.pelny_adres, ', ', 1, 2)+2, length(wiersz.pelny_adres)-INSTR(wiersz.pelny_adres, ', ', 1, 2)-1);
    
    dbms_output.put_line(l_miejscowosc || '    ' || l_ulica_i_numer || '    ' || l_wojewodztwo);
    
    INSERT INTO zbd_staging.oddział (nazwa, miasto, województwo, ulica_i_numer)
    VALUES (wiersz.nazwa_z_numerem_oddzialu, l_miejscowosc, l_wojewodztwo, l_ulica_i_numer);
    
  end loop;
end;

-- Oracle PL SQL nie oferuje niczego co pozwalałoby odwzorować HashMap<String, ArrayList<String>>, pozostaje więc:
ALTER TABLE spis_kategorii DROP CONSTRAINT kategoria_a_dzial;

DROP TABLE spis_kategorii;
DROP TABLE spis_dzialow;

CREATE TABLE spis_dzialow (
    id number(12) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    CONSTRAINT nazwa_dzialu_pk PRIMARY KEY (id),
    
    nazwa varchar2(40)
);

CREATE TABLE spis_kategorii (
    id number(12) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    CONSTRAINT spis_kategorii_pk PRIMARY KEY (id),
    
    nazwa varchar2(40),
    id_odpowiadajacego_dzialu number(12)
);

ALTER TABLE spis_kategorii ADD CONSTRAINT kategoria_a_dzial
    FOREIGN KEY (id_odpowiadajacego_dzialu)
        REFERENCES spis_dzialow (id) ON DELETE CASCADE;


INSERT INTO spis_dzialow (nazwa) VALUES ('AGD');
INSERT INTO spis_kategorii (nazwa, id_odpowiadajacego_dzialu) VALUES ('lodówki', 1);
INSERT INTO spis_kategorii (nazwa, id_odpowiadajacego_dzialu) VALUES ('suszarki', 1);
INSERT INTO spis_kategorii (nazwa, id_odpowiadajacego_dzialu) VALUES ('kuchenki gazowe', 1);
INSERT INTO spis_kategorii (nazwa, id_odpowiadajacego_dzialu) VALUES ('kuchenki mikrofalowe', 1);
INSERT INTO spis_kategorii (nazwa, id_odpowiadajacego_dzialu) VALUES ('czajniki elektryczne', 1);
INSERT INTO spis_kategorii (nazwa, id_odpowiadajacego_dzialu) VALUES ('golarki i maszynki elektryczne', 1);
INSERT INTO spis_kategorii (nazwa, id_odpowiadajacego_dzialu) VALUES ('okapy', 1);
INSERT INTO spis_kategorii (nazwa, id_odpowiadajacego_dzialu) VALUES ('zmywarki', 1);

INSERT INTO spis_dzialow (nazwa) VALUES ('RTV');
INSERT INTO spis_kategorii (nazwa, id_odpowiadajacego_dzialu) VALUES ('telewizory', 2);
INSERT INTO spis_kategorii (nazwa, id_odpowiadajacego_dzialu) VALUES ('konsole', 2);
INSERT INTO spis_kategorii (nazwa, id_odpowiadajacego_dzialu) VALUES ('sprzęt audio', 2);
INSERT INTO spis_kategorii (nazwa, id_odpowiadajacego_dzialu) VALUES ('kable i przejściówki', 2);
INSERT INTO spis_kategorii (nazwa, id_odpowiadajacego_dzialu) VALUES ('telefony i tablety', 2);

INSERT INTO spis_dzialow (nazwa) VALUES ('artykuły spożywcze');
INSERT INTO spis_kategorii (nazwa, id_odpowiadajacego_dzialu) VALUES ('nabiał', 3);
INSERT INTO spis_kategorii (nazwa, id_odpowiadajacego_dzialu) VALUES ('pieczywo', 3);
INSERT INTO spis_kategorii (nazwa, id_odpowiadajacego_dzialu) VALUES ('ryby', 3);
INSERT INTO spis_kategorii (nazwa, id_odpowiadajacego_dzialu) VALUES ('mięso i wędliny', 3);
INSERT INTO spis_kategorii (nazwa, id_odpowiadajacego_dzialu) VALUES ('mrożonki', 3);
INSERT INTO spis_kategorii (nazwa, id_odpowiadajacego_dzialu) VALUES ('produkty zbożowe', 3);
INSERT INTO spis_kategorii (nazwa, id_odpowiadajacego_dzialu) VALUES ('warzywa i owoce', 3);
INSERT INTO spis_kategorii (nazwa, id_odpowiadajacego_dzialu) VALUES ('słodycze', 3);
INSERT INTO spis_kategorii (nazwa, id_odpowiadajacego_dzialu) VALUES ('napoje', 3);
INSERT INTO spis_kategorii (nazwa, id_odpowiadajacego_dzialu) VALUES ('przekąski', 3);

INSERT INTO spis_dzialow (nazwa) VALUES ('alkohole');
INSERT INTO spis_kategorii (nazwa, id_odpowiadajacego_dzialu) VALUES ('wina czerwone', 4);
INSERT INTO spis_kategorii (nazwa, id_odpowiadajacego_dzialu) VALUES ('wina białe', 4);
INSERT INTO spis_kategorii (nazwa, id_odpowiadajacego_dzialu) VALUES ('whiskey', 4);
INSERT INTO spis_kategorii (nazwa, id_odpowiadajacego_dzialu) VALUES ('likiery', 4);
INSERT INTO spis_kategorii (nazwa, id_odpowiadajacego_dzialu) VALUES ('wódki smakowe', 4);
INSERT INTO spis_kategorii (nazwa, id_odpowiadajacego_dzialu) VALUES ('wódki czyste', 4);
INSERT INTO spis_kategorii (nazwa, id_odpowiadajacego_dzialu) VALUES ('piwa', 4);

INSERT INTO spis_dzialow (nazwa) VALUES ('kosmetyki');  
INSERT INTO spis_kategorii (nazwa, id_odpowiadajacego_dzialu) VALUES ('artykuły do kąpieli', 5);
INSERT INTO spis_kategorii (nazwa, id_odpowiadajacego_dzialu) VALUES ('kremy', 5);
INSERT INTO spis_kategorii (nazwa, id_odpowiadajacego_dzialu) VALUES ('higiena jamy ustnej', 5);
INSERT INTO spis_kategorii (nazwa, id_odpowiadajacego_dzialu) VALUES ('artykuły do makijażu', 5);
INSERT INTO spis_kategorii (nazwa, id_odpowiadajacego_dzialu) VALUES ('perfumy', 5);

INSERT INTO spis_dzialow (nazwa) VALUES ('zabawki');
INSERT INTO spis_kategorii (nazwa, id_odpowiadajacego_dzialu) VALUES ('materiały artystyczne', 6);
INSERT INTO spis_kategorii (nazwa, id_odpowiadajacego_dzialu) VALUES ('zabawki interaktywne', 6);
INSERT INTO spis_kategorii (nazwa, id_odpowiadajacego_dzialu) VALUES ('układanki', 6);
INSERT INTO spis_kategorii (nazwa, id_odpowiadajacego_dzialu) VALUES ('lalki i zabawki pluszowe', 6);
INSERT INTO spis_kategorii (nazwa, id_odpowiadajacego_dzialu) VALUES ('pojazdy', 6);

INSERT INTO spis_dzialow (nazwa) VALUES ('artykuły papiernicze');
INSERT INTO spis_kategorii (nazwa, id_odpowiadajacego_dzialu) VALUES ('szkolne', 7);
INSERT INTO spis_kategorii (nazwa, id_odpowiadajacego_dzialu) VALUES ('biurowe', 7);
INSERT INTO spis_kategorii (nazwa, id_odpowiadajacego_dzialu) VALUES ('artystyczne', 7);

INSERT INTO spis_dzialow (nazwa) VALUES ('dom');
INSERT INTO spis_kategorii (nazwa, id_odpowiadajacego_dzialu) VALUES ('dekoracje i akcesoria', 8);
INSERT INTO spis_kategorii (nazwa, id_odpowiadajacego_dzialu) VALUES ('oświetlenie', 8);
INSERT INTO spis_kategorii (nazwa, id_odpowiadajacego_dzialu) VALUES ('tekstylia', 8);
INSERT INTO spis_kategorii (nazwa, id_odpowiadajacego_dzialu) VALUES ('szafki, regały, stojaki', 8);

INSERT INTO spis_dzialow (nazwa) VALUES ('ogród');
INSERT INTO spis_kategorii (nazwa, id_odpowiadajacego_dzialu) VALUES ('dekoracje ogrodowe', 9);
INSERT INTO spis_kategorii (nazwa, id_odpowiadajacego_dzialu) VALUES ('grille i akcesoria', 9);
INSERT INTO spis_kategorii (nazwa, id_odpowiadajacego_dzialu) VALUES ('meble ogrodowe', 9);
INSERT INTO spis_kategorii (nazwa, id_odpowiadajacego_dzialu) VALUES ('oświetlenie ogrodowe', 9);

INSERT INTO spis_dzialow (nazwa) VALUES ('produkty do sprzątania');
INSERT INTO spis_kategorii (nazwa, id_odpowiadajacego_dzialu) VALUES ('pranie i płukanie', 10);
INSERT INTO spis_kategorii (nazwa, id_odpowiadajacego_dzialu) VALUES ('środki czystości, detergenty', 10);
INSERT INTO spis_kategorii (nazwa, id_odpowiadajacego_dzialu) VALUES ('środki do samochodu i warsztatu', 10);
INSERT INTO spis_kategorii (nazwa, id_odpowiadajacego_dzialu) VALUES ('suszenie i prasowanie', 10);
INSERT INTO spis_kategorii (nazwa, id_odpowiadajacego_dzialu) VALUES ('do podłóg', 10);
INSERT INTO spis_kategorii (nazwa, id_odpowiadajacego_dzialu) VALUES ('do okien', 10);
INSERT INTO spis_kategorii (nazwa, id_odpowiadajacego_dzialu) VALUES ('do mebli', 10);

INSERT INTO spis_dzialow (nazwa) VALUES ('multimedia');
INSERT INTO spis_kategorii (nazwa, id_odpowiadajacego_dzialu) VALUES ('gry konsolowe', 11);
INSERT INTO spis_kategorii (nazwa, id_odpowiadajacego_dzialu) VALUES ('gry PC', 11);
INSERT INTO spis_kategorii (nazwa, id_odpowiadajacego_dzialu) VALUES ('filmy', 11);
INSERT INTO spis_kategorii (nazwa, id_odpowiadajacego_dzialu) VALUES ('muzyka', 11);
INSERT INTO spis_kategorii (nazwa, id_odpowiadajacego_dzialu) VALUES ('książki', 11);

INSERT INTO spis_dzialow (nazwa) VALUES ('odzież');
INSERT INTO spis_kategorii (nazwa, id_odpowiadajacego_dzialu) VALUES ('odzież sportowa', 12);
INSERT INTO spis_kategorii (nazwa, id_odpowiadajacego_dzialu) VALUES ('moda damska', 12);
INSERT INTO spis_kategorii (nazwa, id_odpowiadajacego_dzialu) VALUES ('moda męska', 12);

INSERT INTO spis_dzialow (nazwa) VALUES ('obuwie');
INSERT INTO spis_kategorii (nazwa, id_odpowiadajacego_dzialu) VALUES ('dla dzieci', 13);
INSERT INTO spis_kategorii (nazwa, id_odpowiadajacego_dzialu) VALUES ('sportowe', 13);
INSERT INTO spis_kategorii (nazwa, id_odpowiadajacego_dzialu) VALUES ('obuwie męskie', 13);
INSERT INTO spis_kategorii (nazwa, id_odpowiadajacego_dzialu) VALUES ('obuwie damskie', 13);



    
    
    