DROP TABLE Produkt CASCADE CONSTRAINTS;
DROP TABLE Promocja CASCADE CONSTRAINTS;
DROP TABLE PrzedzialKosztuZamowienia CASCADE CONSTRAINTS;
DROP TABLE Reklamacja CASCADE CONSTRAINTS;
DROP TABLE WielkoscTransakcji CASCADE CONSTRAINTS;
DROP TABLE Czas CASCADE CONSTRAINTS;
DROP TABLE Dostawca CASCADE CONSTRAINTS;
DROP TABLE Fakty_Magazyn CASCADE CONSTRAINTS;
DROP TABLE Fakty_Sprzedaz CASCADE CONSTRAINTS;
DROP TABLE Fakty_Zamowienia CASCADE CONSTRAINTS;
DROP TABLE KategoriaCenowa CASCADE CONSTRAINTS;
DROP TABLE Lokalizacja CASCADE CONSTRAINTS;
DROP TABLE Ocena_Od_Klienta CASCADE CONSTRAINTS;
DROP TABLE Pracownik CASCADE CONSTRAINTS;

