ALTER TABLE Cena
    DROP CONSTRAINT Cena_Produkt;

ALTER TABLE Promocja
    DROP CONSTRAINT Promocja_Produkt;

ALTER TABLE Sprzedaz
    DROP CONSTRAINT Sprzedaz_OcenaKlienta;

ALTER TABLE Sprzedaz
    DROP CONSTRAINT Sprzedaz_Pracownik;

ALTER TABLE Sprzedaz
    DROP CONSTRAINT Sprzedaz_Produkt;

ALTER TABLE Sprzedaz
    DROP CONSTRAINT Sprzedaz_Reklamacja;

ALTER TABLE StanMagazynu
    DROP CONSTRAINT StanMagazynu_Oddzial;

ALTER TABLE StanMagazynu
    DROP CONSTRAINT StanMagazynu_Produkt;

ALTER TABLE ZamowienieProdukt
    DROP CONSTRAINT ZamowienieProdukt_Produkt;

ALTER TABLE ZamowienieProdukt
    DROP CONSTRAINT ZamowienieProdukt_Zamowienie;

ALTER TABLE Zamowienie
    DROP CONSTRAINT Zamowienie_Dostawca;

ALTER TABLE Zamowienie
    DROP CONSTRAINT Zamowienie_Oddzial;

ALTER TABLE Reklamacja
    DROP CONSTRAINT Reklamacja_pk;

DROP TABLE Cena;
DROP TABLE Dostawca;
DROP TABLE OcenaKlienta;
DROP TABLE Oddzial;
DROP TABLE Pracownik;
DROP TABLE Produkt;
DROP TABLE Promocja;
DROP TABLE Sprzedaz;
DROP TABLE Reklamacja;
DROP TABLE StanMagazynu;
DROP TABLE Zamowienie;
DROP TABLE ZamowienieProdukt;


CREATE TABLE Cena (
    id number(12) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    Wartosc decimal(8,2)  NOT NULL,
    DataStartu date  NOT NULL,
    DataKonca date  NOT NULL,
    Produkt_id number(12)  NOT NULL,
    CONSTRAINT Cena_pk PRIMARY KEY (id)
) ;

CREATE TABLE Dostawca (
    id number(12) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    Nazwa varchar2(50)  NOT NULL,
    CONSTRAINT Dostawca_pk PRIMARY KEY (id)
) ;

CREATE TABLE OcenaKlienta (
    id number(12) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    Tresc varchar2(50)  NOT NULL,
    CONSTRAINT OcenaKlienta_pk PRIMARY KEY (id)
) ;

CREATE TABLE Oddzial (
    id number(12) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    Wojewodztwo varchar2(50)  NOT NULL,
    Miasto varchar2(50)  NOT NULL,
    CONSTRAINT id PRIMARY KEY (id)
) ;

CREATE TABLE Pracownik (
    id number(12) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    Imie varchar2(50)  NOT NULL,
    Nazwisko varchar2(50)  NOT NULL,
    CONSTRAINT Pracownik_pk PRIMARY KEY (id)
) ;

CREATE TABLE Produkt (
    id number(12) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    NazwaProduktu varchar2(50)  NOT NULL,
    NazwaDzialu varchar2(50)  NOT NULL,
    NazwaTypu varchar2(50)  NOT NULL,
    CONSTRAINT Produkt_pk PRIMARY KEY (id)
) ;

CREATE TABLE Promocja (
    id number(12) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    WartoscProcentowa integer  NOT NULL,
    DataStartu date  NOT NULL,
    DataKonca date  NOT NULL,
    Produkt_id number(12)  NOT NULL,
    CONSTRAINT Promocja_pk PRIMARY KEY (id)
) ;

CREATE TABLE Reklamacja (
    id number(12) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    Powod varchar2(50)  NOT NULL,
    CONSTRAINT Reklamacja_pk PRIMARY KEY (id)
) ;

CREATE TABLE Sprzedaz (
    id number(12) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    Liczbasztuk number(12)  NOT NULL,
    Zysk float(6)  NOT NULL,
    Data timestamp  NOT NULL,
    Produkt_id number(12)  NOT NULL,
    OcenaKlienta_Id number(12)  NOT NULL,
    Pracownik_id number(12)  NOT NULL,
    Reklamacja_id number(12)  NOT NULL,
    CONSTRAINT Sprzedaz_pk PRIMARY KEY (id)
) ;

CREATE TABLE StanMagazynu (
    Oddzial_id number(12)  NOT NULL,
    LiczbaSztuk number(12)  NOT NULL,
    Data timestamp  NOT NULL,
    Produkt_id number(12)  NOT NULL,
    CONSTRAINT StanMagazynu_pk PRIMARY KEY (Oddzial_id, Produkt_id)
) ;

CREATE TABLE Zamowienie (
    id number(12) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    Data timestamp  NOT NULL,
    LiczbaSztuk number(6) NOT NULL,
    Dostawca_id number(12)  NOT NULL,
    Oddzial_id number(12)  NOT NULL,
    CONSTRAINT Zamowienie_pk PRIMARY KEY (id)
) ;

CREATE TABLE ZamowienieProdukt (
    CenaHurtowa decimal(8,2)  NOT NULL,
    Zamowienie_id number(12)  NOT NULL,
    Produkt_id number(12)  NOT NULL,
    CONSTRAINT ZamowienieProdukt_pk PRIMARY KEY (Zamowienie_id,Produkt_id)
) ;


ALTER TABLE Cena ADD CONSTRAINT Cena_Produkt
    FOREIGN KEY (Produkt_id)
    REFERENCES Produkt (id);

ALTER TABLE Promocja ADD CONSTRAINT Promocja_Produkt
    FOREIGN KEY (Produkt_id)
    REFERENCES Produkt (id);

ALTER TABLE Sprzedaz ADD CONSTRAINT Sprzedaz_OcenaKlienta
    FOREIGN KEY (OcenaKlienta_Id)
    REFERENCES OcenaKlienta (id);

ALTER TABLE Sprzedaz ADD CONSTRAINT Sprzedaz_Pracownik
    FOREIGN KEY (Pracownik_id)
    REFERENCES Pracownik (id);

ALTER TABLE Sprzedaz ADD CONSTRAINT Sprzedaz_Reklamacja
    FOREIGN KEY (Reklamacja_id)
    REFERENCES Reklamacja (id);

ALTER TABLE Sprzedaz ADD CONSTRAINT Sprzedaz_Produkt
    FOREIGN KEY (Produkt_id)
    REFERENCES Produkt (id);

ALTER TABLE StanMagazynu ADD CONSTRAINT StanMagazynu_Oddzial
    FOREIGN KEY (Oddzial_id)
    REFERENCES Oddzial (id);

ALTER TABLE StanMagazynu ADD CONSTRAINT StanMagazynu_Produkt
    FOREIGN KEY (Produkt_id)
    REFERENCES Produkt (id);

ALTER TABLE ZamowienieProdukt ADD CONSTRAINT ZamowienieProdukt_Produkt
    FOREIGN KEY (Produkt_id)
    REFERENCES Produkt (id);

ALTER TABLE ZamowienieProdukt ADD CONSTRAINT ZamowienieProdukt_Zamowienie
    FOREIGN KEY (Zamowienie_id)
    REFERENCES Zamowienie (id);

ALTER TABLE Zamowienie ADD CONSTRAINT Zamowienie_Dostawca
    FOREIGN KEY (Dostawca_id)
    REFERENCES Dostawca (id);

ALTER TABLE Zamowienie ADD CONSTRAINT Zamowienie_Oddzial
    FOREIGN KEY (Oddzial_id)
    REFERENCES Oddzial (id);
